# Generated by Django 3.1.7 on 2021-03-04 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tasklist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='watch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
